openapi: 3.1.0
x-stoplight:
  id: bom8g7wo4f10j
info:
  title: Permission
  version: '1.0'
  description: Endpoints for Flex's Permissions functionality
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  contact:
    name: Support
    url: 'https://www.flex.one'
    email: support@flex.one
  summary: Permission
servers:
  - url: 'http://localhost:3000'
    description: Local
  - url: 'https://platform.flexbase.dev'
    description: Development
  - url: 'https://platform.flex.one'
    description: Production
paths:
  '/permission/accounts/{accountId}/accountRole/{accountRole}':
    parameters:
      - $ref: '#/components/parameters/accountId'
      - $ref: '#/components/parameters/accountRole'
    post:
      summary: Add account role to authentication
      description: Add an account level role to an authentication.
      tags:
        - Permission
      operationId: addAccountRoleToAuthentication
      x-stoplight:
        id: sxhcqjybmpipl
      requestBody:
        $ref: '#/components/requestBodies/RoleTargetBody'
      responses:
        '200':
          description: OK
    delete:
      summary: Remove account role from authentication
      tags:
        - Permission
      responses:
        '200':
          description: OK
      operationId: removeAccountRoleFromAuthentication
      x-stoplight:
        id: 6gh37xe4ae1t6
      description: Remove an account level role from an authentication.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleTarget'
  '/permission/accounts/{accountId}/flexRoles/{flexRole}':
    x-internal: true
    parameters:
      - $ref: '#/components/parameters/flexRole'
      - $ref: '#/components/parameters/accountId'
    post:
      summary: Add flex role to authentication
      description: Add a flex level role to an authentication
      tags:
        - Permission
      operationId: addFlexRoleToAuthentication
      requestBody:
        $ref: '#/components/requestBodies/RoleTargetBody'
      responses:
        '200':
          description: OK
      x-stoplight:
        id: gs9o2076h4kr2
    delete:
      summary: Remove flex role from authentication
      tags:
        - Permission
      responses:
        '200':
          description: OK
      operationId: removeFlexRoleFromAuthentication
      x-stoplight:
        id: s95wfwcxg5a62
      description: Remove a flex level role from an authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleTarget'
  '/permission/accounts/{accountId}/listAccountPermissions':
    parameters:
      - schema:
          type: string
        name: accountId
        in: path
        required: true
    get:
      summary: List account permissions on account
      tags:
        - Permission
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuthenticationRole'
                  x-stoplight:
                    id: ntnwpwght568u
      operationId: listAccountPermissionsOnAccount
      x-stoplight:
        id: r7w3qxxpwcjq4
      description: 'List the permissions that are on and account. '
components:
  schemas:
    RoleTarget:
      title: RoleTarget
      x-stoplight:
        id: jxicuws5cyb4v
      type: object
      description: |-
        Model to help target an authentication for permissions.
        Currently supports email or id lookup.
      properties:
        maybeTargetEmail:
          type: string
          x-stoplight:
            id: o0gfawhw3j6vo
          description: The authentication user_name / email
        maybeTargetAuthenticationId:
          type: string
          x-stoplight:
            id: o0gfawhw3j6vo
          description: The Authentication Id
    AuthenticationRole:
      title: AuthenticationRole
      x-stoplight:
        id: 9q5urbwxh9sv4
      type: object
      required:
        - userName
        - role
      properties:
        userName:
          type: string
          x-stoplight:
            id: 80fe7d24sa4dj
        role:
          type: string
          x-stoplight:
            id: o0gfawhw3j6vo
      description: Model describing an authentication's role
  requestBodies:
    RoleTargetBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RoleTarget'
      description: ''
  parameters:
    accountId:
      name: accountId
      in: path
      required: true
      schema:
        type: string
      description: The Account Identifier
    accountRole:
      name: accountRole
      in: path
      required: true
      schema:
        type: string
      description: The Account Role Identifier
    flexRole:
      name: flexRole
      in: path
      required: true
      schema:
        type: string
      description: The Flex Role Identifier
  securitySchemes:
    token:
      type: http
      scheme: bearer
tags:
  - name: Permission
    description: Permission
